"""Identifier generation boundary."""

from typing import Protocol

from agent_company_os.domain.agent import ActionId, AgentRunId, ObservationId
from agent_company_os.domain.ids import (
    EventId,
    ExecutionId,
    GoalId,
    StateTransitionId,
    TaskAttemptId,
    TaskId,
    WorkspaceId,
)
from agent_company_os.domain.knowledge import EvidencePackId, KnowledgeSourceId
from agent_company_os.domain.tools import ToolInvocationId, ToolReceiptId


class IdGenerator(Protocol):
    def knowledge_source_id(self) -> KnowledgeSourceId: ...
    def evidence_pack_id(self) -> EvidencePackId: ...
    def tool_invocation_id(self) -> ToolInvocationId: ...
    def tool_receipt_id(self) -> ToolReceiptId: ...
    def agent_run_id(self) -> AgentRunId: ...
    def action_id(self) -> ActionId: ...
    def observation_id(self) -> ObservationId: ...
    def workspace_id(self) -> WorkspaceId: ...
    def goal_id(self) -> GoalId: ...
    def task_id(self) -> TaskId: ...
    def task_attempt_id(self) -> TaskAttemptId: ...
    def execution_id(self) -> ExecutionId: ...
    def event_id(self) -> EventId: ...
    def state_transition_id(self) -> StateTransitionId: ...
