"""Identifier generation boundary."""

from typing import Protocol

from agent_company_os.domain.agent import ActionId, AgentRunId, ObservationId
from agent_company_os.domain.communication import AgentMessageId, HandoffId, MessageThreadId
from agent_company_os.domain.ids import (
    EventId,
    ExecutionId,
    GoalId,
    StateTransitionId,
    TaskAttemptId,
    TaskId,
    WorkspaceId,
)
from agent_company_os.domain.knowledge import EvidencePackId, KnowledgeSourceId
from agent_company_os.domain.memory import MemoryCandidateId, MemoryContextPackId, MemoryEntryId
from agent_company_os.domain.orchestration import (
    DelegationId,
    OrchestrationPlanId,
    OrchestrationRunId,
)
from agent_company_os.domain.organization_ids import (
    CapabilityId,
    DepartmentId,
    OrganizationGraphId,
    OrgRoleId,
)
from agent_company_os.domain.tools import ToolInvocationId, ToolReceiptId


class IdGenerator(Protocol):
    def organization_graph_id(self) -> OrganizationGraphId: ...
    def department_id(self) -> DepartmentId: ...
    def org_role_id(self) -> OrgRoleId: ...
    def capability_id(self) -> CapabilityId: ...
    def agent_message_id(self) -> AgentMessageId: ...
    def message_thread_id(self) -> MessageThreadId: ...
    def handoff_id(self) -> HandoffId: ...
    def orchestration_run_id(self) -> OrchestrationRunId: ...
    def orchestration_plan_id(self) -> OrchestrationPlanId: ...
    def delegation_id(self) -> DelegationId: ...
    def memory_candidate_id(self) -> MemoryCandidateId: ...
    def memory_entry_id(self) -> MemoryEntryId: ...
    def memory_context_pack_id(self) -> MemoryContextPackId: ...
    def knowledge_source_id(self) -> KnowledgeSourceId: ...
    def evidence_pack_id(self) -> EvidencePackId: ...
    def tool_invocation_id(self) -> ToolInvocationId: ...
    def tool_receipt_id(self) -> ToolReceiptId: ...
    def agent_run_id(self) -> AgentRunId: ...
    def action_id(self) -> ActionId: ...
    def observation_id(self) -> ObservationId: ...
    def workspace_id(self) -> WorkspaceId: ...
    def goal_id(self) -> GoalId: ...
    def task_id(self) -> TaskId: ...
    def task_attempt_id(self) -> TaskAttemptId: ...
    def execution_id(self) -> ExecutionId: ...
    def event_id(self) -> EventId: ...
    def state_transition_id(self) -> StateTransitionId: ...
