"""Identifier generation boundary."""

from typing import Protocol

from agent_company_os.domain.agent import ActionId, AgentRunId, ObservationId
from agent_company_os.domain.ids import (
    EventId,
    ExecutionId,
    GoalId,
    StateTransitionId,
    TaskAttemptId,
    TaskId,
    WorkspaceId,
)


class IdGenerator(Protocol):
    def agent_run_id(self) -> AgentRunId: ...
    def action_id(self) -> ActionId: ...
    def observation_id(self) -> ObservationId: ...
    def workspace_id(self) -> WorkspaceId: ...
    def goal_id(self) -> GoalId: ...
    def task_id(self) -> TaskId: ...
    def task_attempt_id(self) -> TaskAttemptId: ...
    def execution_id(self) -> ExecutionId: ...
    def event_id(self) -> EventId: ...
    def state_transition_id(self) -> StateTransitionId: ...
