"""Used operator identity persistence and cryptographic entropy boundaries."""

from contextlib import AbstractContextManager
from typing import Protocol

from agent_company_os.domain.ids import Version, WorkspaceId
from agent_company_os.domain.operator import (
    OperatorAccount,
    OperatorAudit,
    OperatorId,
    OperatorSession,
)


class OperatorSecrets(Protocol):
    def issue(self) -> str: ...


class OperatorStore(Protocol):
    def atomic(self) -> AbstractContextManager[None]: ...
    def add_account(self, account: OperatorAccount) -> None: ...
    def account(self, principal_id: OperatorId) -> OperatorAccount | None: ...
    def credential(self, digest: str) -> OperatorAccount | None: ...
    def disable(self, principal_id: OperatorId, expected: Version) -> None: ...
    def add_session(self, session: OperatorSession) -> None: ...
    def session(self, digest: str) -> OperatorSession | None: ...
    def revoke_session(self, digest: str) -> None: ...
    def append_audit(self, event: OperatorAudit) -> None: ...
    def audit(self, workspace: WorkspaceId) -> tuple[OperatorAudit, ...]: ...
