"""Persistence seam for canonical state plus append-only audit history."""

from typing import Protocol

from agent_company_os.domain.events import Event
from agent_company_os.domain.execution import Execution
from agent_company_os.domain.goal import Goal
from agent_company_os.domain.ids import (
    ExecutionId,
    GoalId,
    TaskAttemptId,
    TaskId,
    Version,
    WorkspaceId,
)
from agent_company_os.domain.task import Task
from agent_company_os.domain.task_attempt import TaskAttempt
from agent_company_os.domain.transitions import StateTransition
from agent_company_os.domain.workspace import Workspace


class DomainStore(Protocol):
    def add_workspace(self, workspace: Workspace, event: Event) -> None: ...
    def add_goal(self, goal: Goal, event: Event) -> None: ...
    def add_task(self, task: Task, event: Event) -> None: ...
    def add_task_attempt(self, attempt: TaskAttempt, event: Event) -> None: ...
    def add_execution(self, execution: Execution, event: Event) -> None: ...

    def get_workspace(self, entity_id: WorkspaceId) -> Workspace: ...
    def get_goal(self, entity_id: GoalId) -> Goal: ...
    def get_task(self, entity_id: TaskId) -> Task: ...
    def get_task_attempt(self, entity_id: TaskAttemptId) -> TaskAttempt: ...
    def get_execution(self, entity_id: ExecutionId) -> Execution: ...

    def save_goal(
        self, goal: Goal, expected_version: Version, transition: StateTransition, event: Event
    ) -> None: ...
    def save_task(
        self, task: Task, expected_version: Version, transition: StateTransition, event: Event
    ) -> None: ...
    def save_task_attempt(
        self,
        attempt: TaskAttempt,
        expected_version: Version,
        transition: StateTransition,
        event: Event,
    ) -> None: ...
    def save_execution(
        self,
        execution: Execution,
        expected_version: Version,
        transition: StateTransition,
        event: Event,
    ) -> None: ...

    def tasks_for_goal(self, goal_id: GoalId) -> tuple[Task, ...]: ...
    def attempts_for_task(self, task_id: TaskId) -> tuple[TaskAttempt, ...]: ...
    def attempts_for_execution(self, execution_id: ExecutionId) -> tuple[TaskAttempt, ...]: ...
    def events(self, workspace_id: WorkspaceId | None = None) -> tuple[Event, ...]: ...
    def transitions(
        self, workspace_id: WorkspaceId | None = None
    ) -> tuple[StateTransition, ...]: ...
